version: '2'
services:
  magasinfacture-app:
    image: magasinfacture
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://magasinfacture-postgresql:5432/magasinFacture
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 9292:9292
  magasinfacture-postgresql:
    extends:
      file: postgresql.yml
      service: magasinfacture-postgresql
